spring:
  datasource:
    url: jdbc:mysql://localhost:3306/order?useUnicode=yes&characterEncoding=UTF-8
    username: ${DB_USER:root}
    password: ${DB_USER:root}

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
        globally_quoted_identifiers: true
        hbm2ddl:
          auto: none
        show_sql: false
        format_sql: true
        use_sql_comments: false
        bytecode: none
        generate_statistics: false
        default_schema: ${SCHEMA_NAME:order}
    database: MYSQL

  # =========== RabbitMQ ============ #

  rabbitmq:
    host: ${RABBITMQ_HOST:127.0.0.1}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USERNAME:guest}
    password: ${RABBITMQ_PASSWORD:guest}
    listener:
      simple:
        default-requeue-rejected: false

  # =========== Flyway ============ #

  flyway:
    locations: classpath:db/migration/
    enabled: true
    create-schemas: true
    schemas: ${SCHEMA_NAME:order}
    placeholder-replacement: false

  # =========== Email Configurations ============ #

  # =========== Custom Queue Definitions ============ #
  mail:
    host: smtp.gmail.com
    port: 587
    username: melita@melita.com
    password: 123456
    properties:
      mail:
        smtp:
          auth: true
        starttls:
          enable: true

amqp:
  config:
    order-exchange: ${ORDER_EXCHANGE:order_topic_exchange}
    order-queue: ${ORDER_QUEUE:order_queue}
    order-routing-key: ${ORDER_ROUTE_KEY:order.fulfillment}

melita:
  feign:
    external-connect-timeout: ${MELITA_NETWORK_EXTERNAL_CON_TIME_OUT:5000}
    external-read-timeout: ${MELITA_NETWORK_EXTERNAL_READ_TIME_OUT:8000}
    external-max-attempt: ${MELITA_NETWORK_EXTERNAL_MAX_ATTEMPT:3}
    external-retry-period: ${MELITA_NETWORK_EXTERNAL_RETRY_PERIOD:200}
  client:
    fulfillment-url: ${ORDER_FULFILLMENT_SERVER_URL:http://localhost:8080}